import { DB_PERMISSIONS, PERMISSIONS, type Permission } from '@/types/rbac';

const PERMISSION_ALIASES: Record<string, string[]> = {
  [PERMISSIONS.VIEW_HOME]: [
    DB_PERMISSIONS.REPORTS_VIEW,
    DB_PERMISSIONS.CLIENTS_MANAGE,
    DB_PERMISSIONS.LOANS_MANAGE,
    DB_PERMISSIONS.PAYMENTS_CREATE,
    DB_PERMISSIONS.CASH_MANAGE,
    DB_PERMISSIONS.EXPENSES_MANAGE,
    DB_PERMISSIONS.USERS_MANAGE,
  ],
  [PERMISSIONS.VIEW_MODULES]: [
    DB_PERMISSIONS.USERS_MANAGE,
    DB_PERMISSIONS.ROLES_MANAGE,
    DB_PERMISSIONS.REPORTS_VIEW,
    DB_PERMISSIONS.CLIENTS_MANAGE,
    DB_PERMISSIONS.LOANS_MANAGE,
  ],
  [PERMISSIONS.VIEW_ROADMAP]: [DB_PERMISSIONS.USERS_MANAGE, DB_PERMISSIONS.ROLES_MANAGE],
  [PERMISSIONS.VIEW_PROFILE]: [
    DB_PERMISSIONS.USERS_MANAGE,
    DB_PERMISSIONS.ROLES_MANAGE,
    DB_PERMISSIONS.CLIENTS_MANAGE,
    DB_PERMISSIONS.LOANS_MANAGE,
    DB_PERMISSIONS.PAYMENTS_CREATE,
    DB_PERMISSIONS.CASH_MANAGE,
    DB_PERMISSIONS.EXPENSES_MANAGE,
    DB_PERMISSIONS.REPORTS_VIEW,
  ],
  [PERMISSIONS.MANAGE_USERS]: [DB_PERMISSIONS.USERS_MANAGE, DB_PERMISSIONS.ROLES_MANAGE],
  [PERMISSIONS.CLOSE_ANY_COLLECTOR_CASHBOX]: [DB_PERMISSIONS.CASH_MANAGE],
  [PERMISSIONS.REGISTER_EXPENSE]: [DB_PERMISSIONS.EXPENSES_MANAGE],
};

export function can(permission: Permission, userPermissions: Permission[] = []) {
  if (userPermissions.includes(permission)) {
    return true;
  }

  const aliases = PERMISSION_ALIASES[permission];
  if (!aliases) {
    return false;
  }

  return aliases.some((alias) => userPermissions.includes(alias));
}
